# Generated by Django 4.1 on 2023-09-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preparation_time', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1)),
                ('dish_type', models.CharField(choices=[('B', 'Breakfast'), ('B2', 'Brunch'), ('D', 'Dinner'), ('D2', 'Dessert'), ('S', 'Supper')], default='B', max_length=2)),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_calories', models.IntegerField()),
                ('dish_description', models.CharField(max_length=1000, null=True)),
                ('dish_owner', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_calories', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_carbs', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User_Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_day_name', models.CharField(max_length=50)),
                ('user_day_dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='disher.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_products',
            field=models.ManyToManyField(to='disher.product'),
        ),
    ]
