# Generated by Django 4.1 on 2024-01-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disher', '0002_rename_user_day_id_user_day_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_amount',
            name='unit',
            field=models.CharField(default="'gr'", max_length=5),
            preserve_default=False,
        ),
    ]
