# Generated by Django 4.1 on 2023-09-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disher', '0002_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_amount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
