# Generated by Django 4.1 on 2023-09-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disher', '0003_alter_product_amount_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount',
            name='product_name',
        ),
        migrations.AddField(
            model_name='product_amount',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
