# Generated by Django 4.1 on 2024-10-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disher', '0005_alter_user_favourite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_favourite',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
